language: rust
cache: cargo

rust:
  - 1.33.0
  - stable
  - beta
  - nightly

env:
  - CARGO_FEATURES=""
  - CARGO_FEATURES="memory_usage"
  - CARGO_FEATURES="serialization"
  - CARGO_FEATURES="lsp"

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - set -ex
  - cargo build --verbose --no-default-features --features="$CARGO_FEATURES"
  - cargo test --verbose --no-default-features --features="$CARGO_FEATURES"
